### PR TITLE
Support for services instead of script entities

### PR DESCRIPTION
**Pull request by infeeeee**
Hello.

Thank you for maintaining this project.

I added support for adding data to movement commands, so it's not necessary to create a separate script for each command anymore.

Related feature request from this discussion: #32 

I didn't remove the old entity configs, for backward compatibility, however users will get a deprecation warning to migrate to the new config. I think the old name would be confusing in this case for new users, as you can call any service with them, not just script entities.

Please correct me if I made some mistakes, this is the first time I contribute to a ha component. I tested my changes in a fresh ha container.

### CODE REVIEW

**Comment by nagyrobi** [comment]
This is a step backwards than using a script imho, because as far as I can see, only one service can be called, whilst when using a script the big advantage is that you can use a sequence of scripts, moreover, you can do automations to queue the RF commands etc. Of course a service can still call a script but that's too cumbersome - that's why I don't agree to deprecate the previous behavior, sorry.

**Comment by infeeeee** [comment]
You can also call a script, I updated the readme, the old config still works, so it doesn't remove any functionality, it just adds more. 

I can remove the deprecation warning, and in that case existing users wouldn't even notice anything. I wanted to rename the config, because it can be confusing, that the name of the config is `...entitiy_id` though it accepts services as well. For the naming scheme I followed universal media player integration: https://www.home-assistant.io/integrations/universal/ Its configs are similar, and it can also has children entities

I have 9 covers, and I manage them via MQTT. For the 9 covers, I had to create 9 cover entities, and 27 scripts, for each direction and stop. It was a huge PITA to create the 27 scripts. With this change I wouldn't have to create any scripts, as I would call the mqtt.service service from the cover entities.

On the readme, the example with mqtt could be removed as well, as in that case you wouldn't need any scripts at all! I can write a new full example with the same functionality.

So yes, for rf based covers this doesn't add anything new, but it makes the life of mqtt users much more easier.

**Comment by nagyrobi** [comment]
This integration works very well the way it is, let's not nag existing users with deprecations etc. If they want to do any change, it can be their choice later, but I don't want to force anyone do any migration if things are working fine the way they already are.

I have 11 covers and yes, it's a pita to make so many scripts. But why is that a problem? I made them _once_ 4 years ago and they work fine since. It was worth the effort.

**Comment by nagyrobi** [comment]
I think I'd rather suggest to fork and create a separate integration with your functionality. You could think of further improvements like config flow support, more recent xknx dependency etc.

**Comment by infeeeee** [comment]
I just read how the `cover_entity_id` config work, and maybe I can switch to that. I just have to create an MQTT cover for each cover and than drive it from this one. At least only 9 unnecessary entities instead of 27...

I want to change how I manage them, because I set up a long time ago, and my MQTT network grew considerably since then. The script ui in ha is unusable because of the same scripts again and again and again.

**Comment by nagyrobi** [comment]
> MQTT network grew considerably since then

One of the reasons why I switched most of my nodes to ESPHome, which uses a direct API connection - far more stable - instead of MQTT.

**Pull request closed without merging**
